# Generated by Django 2.2.7 on 2019-11-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_entry_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
