# Generated by Django 2.2.7 on 2019-11-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
