# Generated by Django 2.2.7 on 2019-11-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_remove_comment_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
